Return calibration points together with map
DeebotUniverse/client.py pull request #423
Opened 2024-02-12 19:25 UTC by philek

I would like to take a stab at adding the calibration points to support the Vacuum Map card from this issue:
https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/321

First step is to calculate such points in the client library.

My Python experience is very limited, so let me know if you would like me to refactor it somehow.

2024-02-14 08:23 UTC, edenhaus requested changes

2024-02-16 19:05 UTC, philek commented on deebot_client/map.py
> +        svg_map = svg.SVG(width=manipulation.x.svg_max, height=manipulation.y.svg_max)
When the SVG image has no size it makes it difficult (or impossible) for the Vacuum Map card to translate the vacuum coordinates back to the map after the image gets scaled again in the Home Assistant UI. 
![image](https://github.com/DeebotUniverse/client.py/assets/17180382/3526fd43-e019-4f2f-9ed3-5815b1306641)


For example in my case the viewport size is 229x237, but Chrome reports the naturalWidth/naturalHeight as 145x150. I believe height is always 150 and width is proportional. Firefox returns 0 for both naturalWidth and naturalHeight. The viewport size is not readily available.
![image](https://github.com/DeebotUniverse/client.py/assets/17180382/5549bc94-36ec-489a-aa8b-1e9a6875f2df)

However, if we set the width and height explicitly for the SVG then its available as naturalWidth/naturalHeight and the coordinate mapping works correctly.
![image](https://github.com/DeebotUniverse/client.py/assets/17180382/576428cd-8824-492e-aac9-1e4669e3a2c3)

2024-02-19 11:12 UTC, PiotrMachowski commented on deebot_client/map.py
> +        svg_map = svg.SVG(width=manipulation.x.svg_max, height=manipulation.y.svg_max)
@edenhaus I haven't tried using the map card with SVG yet, I'll have to check it out.

2024-02-24 19:36 UTC, edenhaus commented
Replaced by #433

2024-02-24 19:36 UTC, closed without merging